
const arabicDigits = n => String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
const state={category:'all',query:'',sort:'asc',limit:12,favorites:new Set(JSON.parse(localStorage.getItem('mazaya-favs')||'[]').map(Number)),favOnly:false,current:null};
const cards=document.getElementById('cards'),chips=document.getElementById('categoryChips'),searchInput=document.getElementById('searchInput'),sortSelect=document.getElementById('sortSelect'),resultCount=document.getElementById('resultCount'),moreBtn=document.getElementById('moreBtn'),favCount=document.getElementById('favCount'),favNav=document.getElementById('favNav');
const modal=document.getElementById('modal'),viewerImage=document.getElementById('viewerImage'),viewerCanvas=document.getElementById('viewerCanvas'),viewerMeta=document.getElementById('viewerMeta'),viewerTitle=document.getElementById('viewerTitle'),pdfPageLink=document.getElementById('pdfPageLink');
function saveFavs(){localStorage.setItem('mazaya-favs',JSON.stringify([...state.favorites]));favCount.textContent=arabicDigits(state.favorites.size)}
function makeChips(){const all=[{key:'all',icon:'◈',label:'جميع التصنيفات'},...MAZAYA_CATEGORIES];chips.innerHTML=all.map(c=>`<button class="chip ${c.key==='all'?'active':''}" data-cat="${c.key}"><span>${c.icon}</span>${c.label}</button>`).join('');chips.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;state.category=b.dataset.cat;state.favOnly=false;state.limit=12;[...chips.children].forEach(x=>x.classList.toggle('active',x===b));render()})}
function filtered(){let a=MAZAYA_PAGES.filter(p=>state.category==='all'||p.category===state.category);if(state.favOnly)a=a.filter(p=>state.favorites.has(p.page));const q=state.query.trim().toLowerCase();if(q)a=a.filter(p=>(p.text+' '+p.categoryLabel+' '+p.page).toLowerCase().includes(q));a=[...a].sort((x,y)=>state.sort==='asc'?x.page-y.page:y.page-x.page);return a}
function render(){const all=filtered();const shown=all.slice(0,state.limit);resultCount.textContent=`${arabicDigits(all.length)} صفحة من العروض${state.favOnly?' في المفضلة':''}`;cards.innerHTML=shown.length?shown.map(p=>`<article class="card"><div class="thumb" data-open="${p.page}" tabindex="0" role="button" aria-label="استعراض ${p.categoryLabel}، صفحة ${p.page}"><img src="${p.image}" loading="lazy" alt="معاينة صفحة ${p.page} من نشرة مزايا"><span class="page-badge">صفحة ${arabicDigits(p.page)}</span></div><div class="card-body"><div class="card-meta">${p.icon} ${p.categoryLabel}</div><div class="card-actions"><button class="open-btn" data-open="${p.page}" type="button">استعراض الصفحة ↗</button><button class="fav-btn ${state.favorites.has(p.page)?'on':''}" data-fav="${p.page}" type="button" aria-label="إضافة إلى المفضلة">${state.favorites.has(p.page)?'♥':'♡'}</button></div></div></article>`).join(''):'<div class="empty">لا توجد صفحات مطابقة لهذه التصفية.</div>';moreBtn.hidden=shown.length>=all.length;saveFavs()}
function openPage(pageNo){const p=MAZAYA_PAGES.find(x=>x.page===Number(pageNo));if(!p)return;state.current=p.page;viewerImage.src=p.image;viewerImage.alt=`صفحة ${p.page} - ${p.categoryLabel}`;viewerMeta.textContent=`أكتوبر ٢٠٢٦ · صفحة ${arabicDigits(p.page)} · ${p.categoryLabel}`;viewerTitle.textContent=`استعراض ${p.categoryLabel}`;pdfPageLink.href=`assets/mazaya-october-2026.pdf#page=${p.page}`;viewerCanvas.classList.remove('zoomed');modal.hidden=false;document.body.style.overflow='hidden'}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function neighbor(delta){const a=filtered();const i=a.findIndex(x=>x.page===state.current);if(i>=0&&a[i+delta])openPage(a[i+delta].page)}
cards.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const n=Number(fav.dataset.fav);state.favorites.has(n)?state.favorites.delete(n):state.favorites.add(n);render();return}const op=e.target.closest('[data-open]');if(op)openPage(op.dataset.open)});cards.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.open){e.preventDefault();openPage(e.target.dataset.open)}});
searchInput.addEventListener('input',()=>{state.query=searchInput.value;state.limit=12;render()});sortSelect.addEventListener('change',()=>{state.sort=sortSelect.value;render()});moreBtn.addEventListener('click',()=>{state.limit+=12;render()});document.getElementById('resetBtn').addEventListener('click',()=>{state.category='all';state.query='';state.sort='asc';state.favOnly=false;state.limit=12;searchInput.value='';sortSelect.value='asc';[...chips.children].forEach((x,i)=>x.classList.toggle('active',i===0));render()});favNav.addEventListener('click',()=>{state.favOnly=!state.favOnly;state.category='all';state.limit=100;[...chips.children].forEach((x,i)=>x.classList.toggle('active',i===0));render();document.getElementById('offers').scrollIntoView({behavior:'smooth'})});
modal.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal()});document.getElementById('prevBtn').addEventListener('click',()=>neighbor(-1));document.getElementById('nextBtn').addEventListener('click',()=>neighbor(1));document.getElementById('zoomBtn').addEventListener('click',()=>viewerCanvas.classList.toggle('zoomed'));document.addEventListener('keydown',e=>{if(modal.hidden)return;if(e.key==='Escape')closeModal();if(e.key==='ArrowLeft')neighbor(1);if(e.key==='ArrowRight')neighbor(-1)});
makeChips();saveFavs();render();
